INSERT INTO departments (department_id, department_name, manager_id, location_id) VALUES (10, 'Administración', 200, 1700);
INSERT INTO departments (department_id, department_name, manager_id, location_id) VALUES (20, 'Marketing', 201, 1800);
INSERT INTO departments (department_id, department_name, manager_id, location_id) VALUES (30, 'Puestos Directivos', 114, 1700);
INSERT INTO departments (department_id, department_name, manager_id, location_id) VALUES (40, 'Recursos Humanos', 203, 2400);
INSERT INTO departments (department_id, department_name, manager_id, location_id) VALUES (50, 'Finanzas', 204, 1700);
INSERT INTO departments (department_id, department_name, manager_id, location_id) VALUES (60, 'Tecnología', 205, 1700);
INSERT INTO departments (department_id, department_name, manager_id, location_id) VALUES (70, 'Soporte Técnico', 206, 1700);
INSERT INTO departments (department_id, department_name, manager_id, location_id) VALUES (80, 'Ventas', 207, 2500);
INSERT INTO departments (department_id, department_name, manager_id, location_id) VALUES (90, 'Logística', 208, 2700);
INSERT INTO departments (department_id, department_name, manager_id, location_id) VALUES (100, 'Compras', 209, 2800);