CREATE TABLE Huerto(id INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(50));
CREATE TABLE Persona(id INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(50));
CREATE TABLE personas_huertos(persona_id INT PRIMARY KEY, huerto_id INT PRIMARY KEY);